/* NOTE: zbase has two branches: master and Yi. 
 * We use master branch here. 
 * One feature of master is that we need to read XPFSA as PFSA!
 * 
 * And for some reason, we must have the following code for it to be made (even if it is not used in any way.)
 * 	string configfile = "config.cfg";
 * 	CONFIG cfg(configfile);
 *
 * Ways to get gamma, the causal coefficient.
 * Given an input and an output sequence, we compare three ways to estimate gammaL:
 * 1. instantiate a genESeSS_x and get gamma. 
 * 	- note: in this approach, the input PFSA is NOT inferred. 
 * 	  Only a XPFSA is inferred and gamma is calculated by running the input through the XPFSA(s);
 * 2. Infer PFSA and XPFSA, and use closed-form formula;
 * 3. Use the finite-depth gamma estimation developed by Yi;
 *
 * The question is how the three ways correlated. 
 *
 * To test the correlation of the three approaches, I plan to do the following:
 * 1. Generate sequences from PFSA and XPFSA pair. 
 * 	- That is, the input is generated by a PFSA, 
 * 	  and the outptu is generated by running the input through an XPFSA. 
 * 2. For simplicity, let us start with randomly generated by M2 for PFSA, 
 *    and randomly generated M4 for XPFSA.   
 * 3. Calculate the three gammas and study their correlation. 
 *    (Also generate 3d plot of the dots to visualize them)
 *
 * Step one: do the above for just one pair of PFSA and XPFSA.
 * Step two: incorporate the random generating part of zbase in Yi's branch to the master.
 *
 * ----------------------------------LOG-----------------------------------
 *  March 4, 13:13
 *  - I decide to only compare gamma calculation 1 and 3,
 *    since 1 is not very stable.
 *    Use following pairs whose (estimated) gammas are relatively bigger.
 *    	1. 
 *    	- PFSA: /home/yhuang10/D3M/zutil_/cfgfiles/PFSA_M2_3.cfg
 *    	- XPFSA: /home/yhuang10/D3M/zutil_/cfgfiles/PFSA_2_4_7.cfg
 *    	2. 
 *    	- PFSA: /home/yhuang10/D3M/zutil_/cfgfiles/PFSA_M2_7.cfg
 *    	- XPFSA: /home/yhuang10/D3M/zutil_/cfgfiles/PFSA_2_4_3.cfg
 */


#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include <boost/tokenizer.hpp>
#include <boost/token_functions.hpp>
#include <exception>
#include <boost/timer/timer.hpp>

#include <time.h>

#include "semantic.h"
#include "config.h"

using namespace boost::program_options;

const string currentDateTime() 
{
    time_t now = time(0);
    struct tm tstruct;
    char buf[80];
    tstruct = *localtime(&now);
	strftime(buf, sizeof(buf), "%m%d-%X", &tstruct);
    
	return buf;
}

typedef map<unsigned int, vector<unsigned int>> DataPhi;

double get_entropy(const vector<unsigned int>& count)
{
	unsigned int sum = 0;
	double entropy = 0.;
	for (unsigned int c : count)
	{
		sum += c;
		if (c > 0)
			entropy -= c * log2(c);
	}
	if (sum == 0)
		return -1;
	else
		return entropy / sum + log2(sum);
}

DataPhi get_count(
	const symbol_list_& seq_first, 
	const symbol_list_& seq_second,
	size_t alphabet_first,
	size_t alphabet_second,
	size_t seq_len)
{
	size_t length = (seq_first.size() < seq_second.size()) ? seq_first.size() : seq_second.size();

	vector<unsigned int> init;
	for (unsigned int i = 0; i < length; i++)
	{
		init.push_back(i);
	}

	DataPhi odp; 
	odp[0] = init;
	
	DataPhi::iterator itr;

	for (unsigned int sl = 0; sl < seq_len; sl++)
	{
		DataPhi ndp;
		
		for (itr = odp.begin(); itr != odp.end(); ++itr)
		{
			unsigned int wordSig = itr->first;
			for (unsigned int index : itr->second)
			{
				unsigned int i = index + sl;
				if (i < length)
				{
					ndp[wordSig * alphabet_first + seq_first[i]].push_back(index);
				}
			}
		}
		odp = ndp;
	}
	
	DataPhi counts;
	for (itr = odp.begin(); itr != odp.end(); ++itr)
	{	
		vector<unsigned int> count(alphabet_second, 0);

		for (unsigned int index : itr->second)
		{
			unsigned int i = index + seq_len;
			if (i < length)
			{
				count[seq_second[i]] += 1;
			}
		}
		counts[itr->first] = count;
		
		// cout << itr->first << ": ";
		// for (unsigned int c : count)
		// 	cout << std::dec << c << " ";
		// cout << get_entropy(count) << endl;
	}
	return counts;
}


double get_entropy( 
	const symbol_list_& seq, 
	size_t alphabet,
	size_t seq_len)
{
	DataPhi counts = get_count(seq, seq, alphabet, alphabet, seq_len);

	double entropy_avg = 0.;
	
	DataPhi::iterator itr;
	for (itr = counts.begin(); itr != counts.end(); ++itr)
	{
		unsigned int sum = 0;
		double entropy = 0.;
		for (unsigned int count: itr->second)
		{
			sum += count;
			if (count > 0)
				entropy -= count * log2(count);
		}
		entropy = entropy / sum + log2(sum);
		entropy_avg += entropy * sum;
	}
	return entropy_avg / (seq.size() - seq_len);
}

double estimate_gamma( 
	const symbol_list_& seq_first, 
	const symbol_list_& seq_second, 
	size_t alphabet_first,
	size_t alphabet_second,
	size_t seq_len)
{
	size_t length = (seq_first.size() < seq_second.size()) ? seq_first.size() : seq_second.size();

	DataPhi counts = get_count(seq_first, seq_second, alphabet_first, alphabet_second, seq_len);
	double entropy = get_entropy(seq_second, alphabet_second, 0);

	double gamma = 0.;

	DataPhi::iterator itr;
	for (itr = counts.begin(); itr != counts.end(); ++itr)
	{
		unsigned int sum = 0;
		for (unsigned int v : itr->second)
			sum += v;
		gamma += get_entropy(itr->second) * sum;
		
	}
	gamma = 1. - gamma / ((length - seq_len) * entropy);
	return gamma;
}

int main(int argc, char *argv[])
{
	const string version="Estimate Gamma Model-free 2020 zed.uchicago.edu";
  	const string EMPTY_ARG_MESSAGE="Exiting. Type -h or --help for usage";
  
	string PFSA_filename;
	string XPFSA_filename;
	size_t length;	// sequence length
	size_t depth;
	size_t num_runs;
	string filename;
	
	// Inferred the parameters
	PFSA G;
	connx aut;
	pitilde pit;
	size_t num_states;
	size_t alphabet;
	
	PFSA H; 
	connx x_aut;
	pitilde x_pit;
	size_t x_num_states;
	size_t x_alphabet;
 	
	options_description desc("### ###\n\
--------------------------\n\
\n\
\n\
\n\
\n\
--------------------------\n\
Example (in ... folder):");
  	desc.add_options()
    ("help,h", "print help message.")
    ("version,V", "print version number")
    ("pfsa,p", value<string>(&PFSA_filename), "PFSA file")
    ("xpfsa,x", value<string>(&XPFSA_filename), "XPFSA file")
    ("length,l", value<size_t>(&length)->default_value(1000), "Length of the sequence")
    ("depth,d", value<size_t>(&depth)->default_value(5), "subsequence length with which the cross derivatives are calculated")
    ("num_runs,n", value<size_t>(&num_runs), "number of runs")
    ("filename,f", value<string>(&filename), "filename for output gamma comparison file (default is current time)");
  	positional_options_description p;
  	variables_map vm;
  	if (argc == 1)
	{
    	cout <<"empty arg, type -h or --help for manual" << endl;
	}
  	try
    {
		store(command_line_parser(argc, argv).options(desc).run(), vm);
      	notify(vm);
    } 
  	catch (std::exception &e)
    {
      	cout << endl << e.what() << endl << desc << endl;
    }

  	if (vm.count("help"))
    {
      	cout << desc << endl;
      	return 1;
    }
  	if (vm.count("version"))
    {
      	cout << version << endl; 
      	return 1;
    }
	if (vm.count("filename")==0)
	{
		filename = "result_" + currentDateTime() + ".dat"; 
	}
	else
	{
		filename += currentDateTime() + ".dat";
	}

	string configfile = "config.cfg";
  	CONFIG cfg(configfile);
  	unsigned int EVALDEPTH = 5;
	unsigned int NUM_EACH = 20;
	gParam parameters(configfile, EVALDEPTH);
  	parameters.NUM_EACH=NUM_EACH;

	
	G = SCC_UTIL__::read_mc(PFSA_filename, "PFSA");
	aut = G.get_aut();
	num_states = aut.size();
	alphabet = aut[0].size();

	H = SCC_UTIL__::read_mc(XPFSA_filename, "XPFSA");
	x_aut = H.get_aut();
	x_pit = H.get_Xpit();
	x_num_states = x_pit.size();
	x_alphabet = x_pit[0].size();

	// G.describe("PFSA G");
	// H.describe("Transducer H");	

	cout << "\n\nCorrelation Study" << endl;
	 
	vector<double> gamma_es(num_runs, 0);
	vector<double> gamma_xg(num_runs, 0);
	for (size_t n = 0; n < num_runs; n++)
	{
		pitilde pit_new = SCC_UTIL__::get_random_pit(aut, 20);
		pitilde x_pit_new = SCC_UTIL__::get_random_pit(x_num_states, x_alphabet, true, .1, 20);

		PFSA G_new(pit_new, aut);
		PFSA H_new(SCC_UTIL__::get_uniform(x_num_states,alphabet), x_aut);
		H_new.set_Xpit(x_pit_new);

		Symbolic_string_ input_ = G_new.gen_data(length);
		Symbolic_string_ output_ = input_ * H_new;
		symbol_list_ input = input_.get_symbol_list();
		symbol_list_ output = output_.get_symbol_list();
		
		genESeSS_x AB(input_, output_, parameters);
		double gamma = AB.gamma();	
		gamma_xg[n] = gamma;
		
		double gamma_1 = estimate_gamma(input, output, alphabet, x_alphabet, depth);
		gamma_es[n] = gamma_1;
		cout << n << ": " << gamma << ", " << gamma_1 << endl;
	}
	

	ofstream log;
	log.open(filename);
	log << "#PFSA=" + PFSA_filename;
	log << ",XPFSA=" + XPFSA_filename;
	log << ",sequence length=" + to_string(length);
	log << ",depth for estimating gamma=" + to_string(depth);
	log << ",numbers of runs=" + to_string(num_runs) << endl;
	log << "xg,est" << endl;
	for (size_t n = 0; n < num_runs; n++)
	{
		log << gamma_xg[n] << "," << gamma_es[n] << endl; 
	}
	log.close();
}
